/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppCommandesRouteImport } from './routes/app.commandes'
import { Route as AppConfirmationsRouteImport } from './routes/app.confirmations'
import { Route as AppRisquesRouteImport } from './routes/app.risques'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandesRoute = AppCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AppRoute,
} as any)
const AppConfirmationsRoute = AppConfirmationsRouteImport.update({
  id: '/confirmations',
  path: '/confirmations',
  getParentRoute: () => AppRoute,
} as any)
const AppRisquesRoute = AppRisquesRouteImport.update({
  id: '/risques',
  path: '/risques',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/clients': typeof AppClientsRoute
  '/app/commandes': typeof AppCommandesRoute
  '/app/confirmations': typeof AppConfirmationsRoute
  '/app/risques': typeof AppRisquesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/clients': typeof AppClientsRoute
  '/app/commandes': typeof AppCommandesRoute
  '/app/confirmations': typeof AppConfirmationsRoute
  '/app/risques': typeof AppRisquesRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/clients': typeof AppClientsRoute
  '/app/commandes': typeof AppCommandesRoute
  '/app/confirmations': typeof AppConfirmationsRoute
  '/app/risques': typeof AppRisquesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/clients'
    | '/app/commandes'
    | '/app/confirmations'
    | '/app/risques'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/clients'
    | '/app/commandes'
    | '/app/confirmations'
    | '/app/risques'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/clients'
    | '/app/commandes'
    | '/app/confirmations'
    | '/app/risques'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commandes': {
      id: '/app/commandes'
      path: '/commandes'
      fullPath: '/app/commandes'
      preLoaderRoute: typeof AppCommandesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/confirmations': {
      id: '/app/confirmations'
      path: '/confirmations'
      fullPath: '/app/confirmations'
      preLoaderRoute: typeof AppConfirmationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risques': {
      id: '/app/risques'
      path: '/risques'
      fullPath: '/app/risques'
      preLoaderRoute: typeof AppRisquesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClientsRoute: typeof AppClientsRoute
  AppCommandesRoute: typeof AppCommandesRoute
  AppConfirmationsRoute: typeof AppConfirmationsRoute
  AppRisquesRoute: typeof AppRisquesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientsRoute: AppClientsRoute,
  AppCommandesRoute: AppCommandesRoute,
  AppConfirmationsRoute: AppConfirmationsRoute,
  AppRisquesRoute: AppRisquesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
